config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  devise_for :users
  get 'orders/index'

  resources :products
  resources :carts
  resources :line_items
  resources :orders
  resources :women
  
  get 'stores/index'

  root to: 'stores#index', as: 'stores'
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id, woman_id: woman_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id, woman_id: woman_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart


  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = ["Credit card", "PayPal" ]

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :women

  #validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true

  def self.latest
    Product.order(:updated_at).last
  end 

  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable
end

app/models/woman.rb
class Woman < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  belongs_to :product

  #validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true

  def self.latest
    Woman.order(:updated_at).last
  end 

  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    @carts = Cart.all
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to @cart, notice: 'Cart was created!'
    else
      render action: 'new'
    end
  end

  def update
    @cart = Cart.find(params[:id])
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Cart successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @cart.destroy 
    if @cart.id == session[:cart_id]
      session[:cart_id] = nil
      redirect_to stores_url
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to stores_url, notice: 'Invalid cart!'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
    
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       render "devise/registrations/edit"
     end
   end

   private
 
   def user_params
     params.require(:user).permit(:name)
   end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
      content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/women_helper.rb
module WomenHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>

app/views/layouts/application.html.erb
<html 'ng-app' true>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shop Now</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller.controller_name %>">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ShopNow", stores_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Products", products_path %><span class="sr-only">(current)</span></li>
          <li class="active"><%= link_to "Women", women_path %><span class="sr-only">(current)</span></li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
          <ul class="nav navbar-nav navbar-right">
            <div class="pull-right user-info">
              <% if current_user %>
                <%= image_tag(current_user.image.tiny.url) if current_user.image? %>
                  <h5>Hi, you're signed in as:</h5> <em><%= link_to (current_user.name || current_user.email), edit_user_registration_path %> </em>
                  <%= link_to "Sign out", destroy_user_session_path, class: 'signout', method: :delete %>
                    <div align = "center"><%= image_tag(current_user.image)%></div> <br>
                <% else %>
                <%= link_to "Sign In", new_user_session_path %> <em>or</em> 
                <%= link_to "Sign Up", new_user_registration_path %><br>
              <% end %>
              <%= link_to "Shopping Cart", @cart %>
            </div>
          </ul>
        </div>
      </div>
    </nav>

    <div id="wrapper">
      <div id="columns">
        <div id="side">
          <% if @cart %> 
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>

    <footer id="footer"> 
      <em>
        Copyright &copy; 2015 Shop Now.
      </em>
    </footer>
  </body>
</html>